### ISSUE TITLE
order undefined on line 27

### ISSUE THREAD

**Issue by aseelaa** [ataluttasgiran/changethewords#1]
Hi,

I just tried your changethewords plugin.  It's great, but I keep seeing an undefined error in the console.  It went away when I commented out the "alert(order);" statement on line 27 in jquery.changethewords.js.

Thanks!
-Aseel

**Comment by talut** [comment]
Hi! Thank for this information.I forgot to delete the line. This line is not necessary. (Sorry for my english :) )

**Comment by aseelaa** [comment]
No problem!  The plugin works great.

**Comment by talut** [comment]
Thanks :)
